In [21]:
print("Hello world!")

Hello world!


name="deep jyoti"
age=19
print(name)
print(age)

In [22]:
name="deep jyoti"
age=19
print(name)
print(age)

deep jyoti
19


In [23]:
a=12
b=20
print("sum=",a+b)
print("difference=",a-b)
print("product=",a*b)

sum= 32
difference= -8
product= 240


In [24]:
name=input("enter your name:")
print("welcome",name)

enter your name:komal
welcome komal


In [25]:
for i in range(1,6):
  print(i)

1
2
3
4
5


In [26]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [27]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [28]:
arr=np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [29]:
arr=np.arange(1,7)
arr=arr.reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
print(arr.shape)

(2, 3)


In [31]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr[2])

30


In [32]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [34]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [35]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [36]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
